server:::
  port: 8888
  servlet:
    context-path: /app
  tomcat:
    max-http-form-post-size: 2GB

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/CvMCM?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 962498546
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/templates
    cache:
      period: 0
mybatis:
  type-aliases-package: com.haoshuai.app.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
